Adding MATRIXX results for version .29
cncf/cnf-certification pull request #7
Opened 2022-05-17 15:11 UTC by EricLo-417

2022-05-17 20:55 UTC, taylor commented
@EricLo-417 a few things:

- please change the folder to v1.0-beta1 instead of v0.29.0 (certification vs test suite)
- please test with the [v0.29.1 release](https://github.com/cncf/cnf-testsuite/releases/tag/v0.29.1) and submit results

2022-05-18 16:10 UTC, agentpoyo commented
@EricLo-417 ,

Looks like the summary posted states `results/cnf-testsuite-results-20220515-170901-190.yml` was generated but looks like that results didn't get updated if you ran v0.29.1 in the files.

2022-05-18 16:23 UTC, taylor requested changes
@EricLo-417 @agentpoyo I see the following in the README
```
2022-05-15 21:33:58 : [runTest001]    [cnfRun]          - 25 of 56 total tests passed
2022-05-15 21:33:58 : [runTest001]    [cnfRun]          - 10 of 13 essential tests passed
2022-05-15 21:33:58 : [runTest001]    [cnfRun]        Results have been saved to results/cnf-testsuite-results-20220515-170901-190.yml
```

note the 0515 vs 0517 for the results.

The results file is v1.0-beta/matrixx-digital-commerce/cnf-testsuite-results-20220517-173143-843.yml

2022-05-18 16:25 UTC, SomethingCreativeStudios commented
Oh I am sorry that was just supposed to be an example of the output. I figured the results file was the thing to matter. Do you still want this sample output updated?

2022-05-18 16:27 UTC, agentpoyo commented
> @EricLo-417 @agentpoyo I see the following in the README
> 
> ```
> 2022-05-15 21:33:58 : [runTest001]    [cnfRun]          - 25 of 56 total tests passed
> 2022-05-15 21:33:58 : [runTest001]    [cnfRun]          - 10 of 13 essential tests passed
> 2022-05-15 21:33:58 : [runTest001]    [cnfRun]        Results have been saved to results/cnf-testsuite-results-20220515-170901-190.yml
> ```
> 
> note the 0515 vs 0517 for the results.
> 
> The results file is v1.0-beta/matrixx-digital-commerce/cnf-testsuite-results-20220517-173143-843.yml

True, I was looking at the last 3 numbers in comparison but I noticed the results file attached to the PR can't be from v0.29.1 since it's missing the tags for the type of test (essential, normal, bonus) and the command that was used to run. @taylor @EricLo-417

2022-05-18 21:45 UTC, EricLo-417 commented
Updated results to use version 0.29.1
Updated readme's example output to use latest results

2022-06-02 15:00 UTC, taylor requested changes
Switch to SVG version

2022-06-02 15:00 UTC, taylor commented on v1.0-beta/matrixx-digital-commerce/PRODUCT.yaml
> +product_logo_url: https://www.dropbox.com/s/ywhib7dh6fxysjl/matrixx_logo_software_color_cmyk.eps?dl=0
```suggestion
product_logo_url: https://www.dropbox.com/s/wrpx3vv1rkowg3h/matrixx_logo_software_color_cmyk.svg?dl=0
```

2022-06-02 15:03 UTC, EricLo-417 commented on v1.0-beta/matrixx-digital-commerce/PRODUCT.yaml
> +product_logo_url: https://www.dropbox.com/s/ywhib7dh6fxysjl/matrixx_logo_software_color_cmyk.eps?dl=0
Updated

2022-06-02 15:18 UTC, taylor approved these changes
lgtm

2022-06-02 19:39 UTC, denverwilliams approved these changes

2022-06-02 19:49 UTC, denverwilliams commented
lgtm

2022-06-14 21:49 UTC, lixuna commented
Remaining Tasks to Complete After PR Review

- [x] Update the Certified CNF spreadsheet to reflect the vendor's certified offering.
- [ ] (in progress) Add the vendor's information to the CNCF landscape which also causes them to appear on https://www.cncf.io/certification/cnf.
- [ ] Add a comment saying "This product is now a "Certified CNF" and merge the PR.

2022-07-06 21:22 UTC, taylor commented
This product is now a "Certified CNF"

2022-07-06 21:22 UTC, merged